source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TwitchTopGames' do
    
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'SVProgressHUD'
    
end

target 'TwitchTopGamesTests' do
    
    pod 'SwiftyJSON', '~> 3.1.4'
    
end

target 'TwitchTopGamesUITests' do
    
end
